# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'page', url: 'about.html'}
- {name: 'All Posts', path: 'page', url: 'all.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/dryotta'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/drdavidzhao?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BQ5MF0LC9QAyv%2BdwQZ5YQ7g%3D%3D'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy:'
related_posts: ''

post_date_prefix: 'Written on'
